### ISSUE TITLE
Having SCHEMA$ field inside generated case class (specific)

### ISSUE THREAD

**Issue by k7i3** [julianpeeters/sbt-avrohugger#101]
Hey! Is there a way to have the SCHEMA$ field not only in the companion object but also within the case class itself? I've tried to experiment with:

`   Compile / avroScalaSpecificCustomTypes := avrohugger.format.SpecificRecord.defaultTypes.copy(
      record = avrohugger.types.ScalaCaseClassWithSchema // ScalaCaseClass
    )
`

and it looks like that for specific records results are the same with both options  🤷‍♂️

**Comment by julianpeeters** [comment]
> Is there a way to have the SCHEMA$ field not only in the companion object but also within the case class itself?

no, there is not
