### ISSUE TITLE
Cannot resolve AvroConfig

### ISSUE THREAD

**Issue by eugenemiretsky** [julianpeeters/sbt-avrohugger#13]
I add the following to my build.sbt file:

> sbtavrohugger.SbtAvrohugger.scavroSettings
> (stringType in avroConfig) := "String"

And get an error: "not found: value sbtavro"

**Comment by julianpeeters** [comment]
Hi Eugene, thanks for the feedback.

This project only generates Scala classes, which already use String by default (see: [Datatypes](https://github.com/julianpeeters/sbt-avrohugger#datatypes)), so there's no need to set the stringType for the Scala side of Scavro.

If you're not already, you'll need to use something like [sbt-avro](https://github.com/sbt/sbt-avro) to generate the Java side of Scavro.

I believe most people are exclusively using the Scala representations/classes in their code, in which case it won't matter what the Java class uses as a String, so might as well use the default Utf-8 for better performance.

But if you have a mixed project and you need the Java classes to use String as well, then see the [ScavroSerializationTests](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/sbt-test/projects/ScavroSerializationTests/build.sbt) for an example of how to change multiple settings in both plugins. Be forewarned that I haven't personally tested changing the stringType setting, but I expect it will work; let me know if you have any further issues and I'll be happy to help sort them out.

**Comment by julianpeeters** [comment]
> I believe most people are exclusively using the Scala representations/classes in their code, in which case it won't matter what the Java class uses as a String, so might as well use the default Utf-8 for better performance.

Oops, this may be misleading. It looks like sbt-avro is using `CharSequence` by default. I've not tested Scavro with the underlying Java using Utf8; it might choke.
