### ISSUE TITLE
avroScalaCustomTypes with array adds invalid constructor to case classes from generateSpecific

### ISSUE THREAD

**Issue by davidhoyt** [julianpeeters/sbt-avrohugger#14]
I have set the following in SBT:

```scala
import sbtavrohugger._, formats.specific._
import SpecificAvroSettings._
import AvrohuggerSettings._

(avroScalaCustomTypes in avroConfig) := Map("array" -> classOf[Array[_]])
```

This generates a case class which adds a default constructor that attempts to use `Nil` for `Array` which causes a compile error in scala 2.10. It would be better to use `Array.empty` or `new Array[T](0)`.

**Comment by davidhoyt** [comment]
I realize this might belong in https://github.com/julianpeeters/avrohugger -- can file a new issue over there if you prefer.

**Comment by julianpeeters** [comment]
Ah, darn. Thanks for the alert. This was a feature for the Scavro format, and it looks like a merged it in without any tests for SpecificRecord format...

Should be easy to fix, tho, just need to make the [matcher package](https://github.com/davidhoyt/avrohugger/tree/master/avrohugger-core/src/main/scala/format/specific/matchers) aware that it needs to check for custom types like the [TypeMatcher](https://github.com/davidhoyt/avrohugger/blob/master/avrohugger-core/src/main/scala/TypeMatcher.scala#L65) does.

If you're not hacking at it away already, I expect to be able to fix it this weekend, but after adding some better protocol support (leaves the matcher package and the Typematcher unaltered).

Many thanks for the report.

**Comment by davidhoyt** [comment]
You're welcome. 😄 I think you know the code best -- for now I'll hand-edit the generated source which will get me through the weekend. Will you be able to make a release this weekend?

**Comment by julianpeeters** [comment]
Yup, looks like it 👍

**Comment by davidhoyt** [comment]
@julianpeeters Any chance you're on gitter?

**Comment by julianpeeters** [comment]
@davidhoyt got sidetracked tracking down some bugs in treehugger, but now coming around the bend.

I'm on gitter, but none of my projects are yet. I'll add avrohugger before closing this ticket.

**Comment by julianpeeters** [comment]
Apologies for the delay. Version 0.10.0 is up at Sonatype, should be syncing with Maven Central in a few hours. Added a gitter badge too. Will be tackling the other issues this week, just wanted to get Array support out first.

Cheers

**Comment by davidhoyt** [comment]
@julianpeeters thanks! 😃
