### ISSUE TITLE
Feature: Support Vector for avroScalaCustomTypes

### ISSUE THREAD

**Issue by davidhoyt** [julianpeeters/sbt-avrohugger#15]
Supporting `Vector` specifically instead of (or at least _in addition to_) `Seq` would be very useful in order to force users to think about run-time semantics for insertion (`big-O`).

If you want to go whole-hog, any type for which there is an `ApplicativePlus`.

**Comment by julianpeeters** [comment]
> Supporting Vector specifically instead of (or at least in addition to) Seq

Great call, will do.

> If you want to go whole-hog, any type for which there is an `ApplicativePlus`

I'm game, but I'm a type-level noob. What the heck is an `ApplicativePlus`? I gather that it's when a container implements `.empty`. What about the `Plus`, is that with respect to the elements (but then I don't see how I could predict that)? How do identify which collection types I should be considering?

**Comment by davidhoyt** [comment]
@julianpeeters `ApplicativePlus`: https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/ApplicativePlus.scala

I would probably ignore that for now -- with code generation it would be too much effort. Basically the idea is that a type class like `ApplicativePlus` proves something about a type. In this case that you can start with something empty and then add to it. It might be more useful for macro annotations but for the code generation part, I'd probably ignore it.

**Comment by julianpeeters** [comment]
So far I've only gotten to [day-0](http://eed3si9n.com/learning-scalaz/day0.html) so this is instructive for me.

>It might be more useful for macro annotations but for the code generation part, I'd probably ignore it

I've heard people express similar sentiments before, but I must admit, having worked with both, I see no relevant differences: both seem to me to do code-generation, only differing in when, what can be generated, and the visibility of the generated code. No obligations of course, but If you've got another digestible tidbit as to what motivates the contrast in this case, I'd love to hear it!

Cheers,

**Comment by julianpeeters** [comment]
`Seq` replaced by `Vector` in version 0.11.0
