### ISSUE TITLE
Move AVSCFileSorter to avrohugger

### ISSUE THREAD

**Issue by davidhoyt** [julianpeeters/sbt-avrohugger#16]
`AVSCFileSorter` is generally useful outside the SBT plugin actually and was wondering if you would consider moving it into avrohugger.

**Comment by julianpeeters** [comment]
Yes, nice idea, it'll be on my TODO.

**Comment by makubi** [comment]
This is being done in julianpeeters/avrohugger#54

**Comment by julianpeeters** [comment]
filesorter is now a module in avrohugger 0.16.0:
`"com.julianpeeters" % "avrohugger-filesorter_2.11" % "0.16.0"`
