### ISSUE TITLE
Add setting to specify enum style for formats other than `SpecificRecord`

### ISSUE THREAD

**Issue by julianpeeters** [julianpeeters/sbt-avrohugger#18]

**Comment by mariussoutier** [comment]
👍

**Comment by julianpeeters** [comment]
Why not case object style as well, while I'm at it. ([feature request](https://github.com/julianpeeters/avrohugger/issues/37))

**Comment by mariussoutier** [comment]
Cool...

**Comment by julianpeeters** [comment]
Sorry for the delay! Got caught up in some other stuff for a bit. If you wanted to try Java enums, you can now use version 0.11.0, adding the following to your build should do the trick.

```scala
import sbtavrohugger.AvrohuggerSettings. avroScalaCustomEnumStyle

(avroScalaCustomEnumStyle in avroConfig) := Map("enum"->"java enum")
```

**Comment by mariussoutier** [comment]
Thanks!
