### ISSUE TITLE
dependency syntax error 

### ISSUE THREAD

**Issue by shubhankar12** [julianpeeters/sbt-avrohugger#20]
build.sbt dependency should be 

"com.julianpeeters" %% "avrohugger-core" % "0.11.0"
                                   ^
instead of 

"com.julianpeeters" % "avrohugger-core" %% "0.11.0"

**Comment by mariussoutier** [comment]
In sbt-avrohugger you should not have to import avrohugger-core, or what are you referring to?

**Comment by julianpeeters** [comment]
oohhhh, must have been this: https://github.com/julianpeeters/avrohugger/pull/39
