### ISSUE TITLE
Missing dependency in case of specific-generator

### ISSUE THREAD

**Issue by kosii** [julianpeeters/sbt-avrohugger#21]
The docs doesn't mention it, but to be able to use `specific-generator` I had to add 

    libraryDependencies += "org.apache.avro" % "avro" % "1.8.1"

to the `build.sbt`. Is it normal? If yes, I'd like to submit a patch for the `README.md`

**Comment by mariussoutier** [comment]
For the sbt plugin to run or for your code to compile?

**Comment by kosii** [comment]
oh! good point, to compile my code

**Comment by mariussoutier** [comment]
Ok, that's to be expected, because an sbt-plugin will not add any library dependencies to your project. And the code generated by the specific-generator will extend from avro's SpecificRecord, hence the need to include the library in your project.

**Comment by kosii** [comment]
yes, it's clear now, thanks!
