### ISSUE TITLE
missing imports in generated classes

### ISSUE THREAD

**Issue by xelax** [julianpeeters/sbt-avrohugger#23]
In updating the plugin from 0.10.1 to 0.11.0 I got a compilation error due to missing import statements. 

I have a record SR in namespace xxx.model.v2 that is refers to types (X, Y, Z) defined  in xxx.model namespace. 
In the 0.10.1 generated code I have an import

import xxx.model.{X, Y, Z} 

that is missing in 0.11.0.

(those are not the actual names of the classes but I hope that this will make sense).
Thanks!

**Comment by julianpeeters** [comment]
Hmm that's odd. While I may have missed something, I expect imports to work for every format (i.e. Standard, Scavro, and Specific formats each have tests with schemas like [this](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/sbt-test/projects/ScavroSerializationTests/src/main/avro/import.avdl)).

Which format are you using (Standard, Scavro, or Specific)?

What does your schema (or idl or protocol) look like? Is it possible to share an simplified, obfuscated schema that I can try to compile to see the problem?

**Comment by xelax** [comment]
I managed to minize the problem. Here is the input file:
`{
  "type": "record",
  "name": "Event",
  "namespace": "protocol",
  "fields": [{
    "name": "sc",
    "type": {
      "name": "SR",
      "fields": [{
        "name": "constraints",
        "type": ["null", {
          "name": "C",
          "fields": [{
            "name": "blah",
            "type": "string"
           }],
          "type": "record",
          "namespace": "model"
        }]
      }],
      "type": "record",
      "namespace": "model.v2"
    }
  }]
}`

**Comment by julianpeeters** [comment]
Thank you for sharing! I appreciate the report and intend to fix this ASAP. My queue is pretty full however, I expect to be able to take a closer look in the next couple weeks.

**Comment by xelax** [comment]
no problem: I can still use 0.10.1 in the meanwhile.

**Comment by julianpeeters** [comment]
👍

**Comment by xelax** [comment]
Any chance that you might give another look at this bug? I switched to scala 2.12 and now i am getting all sorts of warning from the scala compiler about the generated classes, but I can't upgrade to 0.13 until this is fixed. 
Thanks!

**Comment by julianpeeters** [comment]
Yes, getting closer! Been unusually busy, but I've been continuing to poke at it. Some `scripted` tests left to finish up, hopefully this weekend. :+1:

**Comment by julianpeeters** [comment]
Sorry @xelax, going to have to push ETA back one more week.

**Comment by jon-morra-zefr** [comment]
I just ran into this problem as well.  I'm eagerly awaiting a solution too.

**Comment by julianpeeters** [comment]
Thanks for your patience all, this should be fixed now in avrohugger/sbt-avrohugger 0.14.0

**Comment by xelax** [comment]
thanks! appreciated. Works fine for me and solves a bunch of warning in my project with 2.12. Thank you again for your work.
