### ISSUE TITLE
Support usage in test config

### ISSUE THREAD

**Issue by joprice** [julianpeeters/sbt-avrohugger#24]
I'd like to use sbt-avrohugger to generate classes specifically for tests, with the schemas living in `src/test/avro`. With the current plugin, it seems the only way to do this is to create a separate project for tests that contains the avro files in `src/main/avro`. 

I'm not sure what benefits using a config has for this plugin, and perhaps using prefixed keys would be a better design. Instead of using a config, the keys would be prefixed, e.g., `avroGenerateSpecific`, and then could be used in another config, e.g., `test:avroGenerateSpecific`. 

There's some notes on this in the sbt docs: http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Configuration+advices

**Comment by julianpeeters** [comment]
Excellent advice, thank you. My queue is a little full currently, I expect to be able to work on this in the next few weeks.

**Comment by julianpeeters** [comment]
Thanks again @joprice. If this is still of interest to you, this has been fixed for sbt-avrohugger 1.0.0
