### ISSUE TITLE
Bubble up error messages

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/sbt-avrohugger#3]
Currently there's no way of knowing that the problem with your schema is, you just don't see any generated classes. So it'd be nice to see Avro exceptions in the sbt log output.

**Comment by julianpeeters** [comment]
Fixed in release version `0.1.2`

**Comment by mariussoutier** [comment]
Nice, just tested it and works perfectly.

    [error] (avro:generateSpecific) org.apache.avro.compiler.idl.ParseException: Encountered " <STUFF_TO_IGNORE> "! "" at line 101, column 15.
    [error] Was expecting:
    [error]     "{" ...
    [error]

**Comment by julianpeeters** [comment]
Excellent, thanks for reporting
