### ISSUE TITLE
specific generator doesn't honour avroScalaCustomTypes

### ISSUE THREAD

**Issue by umnick84** [julianpeeters/sbt-avrohugger#39]
Hi. In build,sbt I specified such project:
`lazy val root = (project in file("."))
  .settings(sbtavrohugger.SbtAvrohugger.specificAvroSettings: _*)
  .settings((avroScalaCustomTypes in avroConfig) := Map("array"->classOf[Seq[_]]))
  .settings((sourceDirectory in avroConfig) := new java.io.File("src/main/resources/avro"))
  .settings((scalaSource in avroConfig) := sourceManaged.value / "avro-gen")`

After classes are generated I still have mapping array-to-List. But I want to have array-to-Seq mapping. It works fine if I use usual avroSettings, not specific one.

**Comment by julianpeeters** [comment]
Hi, thanks for reporting, I fixed that typo in the README. `Seq` is no longer supported as a custom type mapping, and has been replaced with `Vector`.
