### ISSUE TITLE
Specify avsc definitions in multiple directories.

### ISSUE THREAD

**Issue by geekity** [julianpeeters/sbt-avrohugger#40]
Hi, :)

Is it currently possible to specify and import avsc definitions from multiple directories? I've been poking at the settings `sourceDirectory`, which I believe currently has to be a single file and wasn't sure if this was due to avro (avsc file ordering) issues/limitations or as part of this project.

Ultimately I'm trying to see if there is a handy way of sharing some core avsc definitions across other packages to allow them to extend them.

Thanks and best,

Nina

**Comment by julianpeeters** [comment]
Hey Nina!

Yeah, I think support for something like `sourceDirectories` makes sense ([related issue in avrohugger](https://github.com/julianpeeters/avrohugger/issues/72)). Using the same parser for all directories may be a simple start.

Unfortunately I'm a bit busy for the near future, so I don't know when I'll be able to get to this. Thanks for bringing up the issue tho!

**Comment by julianpeeters** [comment]
This feature was added in avrhohugger version 1.0.0-RC12 and sbt-avrohugger version 2.0.0-RC12, at Sonatype now, and syncing with maven central shortly.
