### ISSUE TITLE
Doesn't support custom fixed types

### ISSUE THREAD

**Issue by RyanSattler** [julianpeeters/sbt-avrohugger#53]
My avdl has a top level field (inside the protocol) like this:

`fixed Bytes16(16);`

Using sbt-avrohugger on this file gives this error:

```
java.lang.RuntimeException: Only RECORD and ENUM can be top-level definitions
```

This page specifies how these values are defined, with an example at the bottom of the page: https://avro.apache.org/docs/1.8.2/idl.html#format_fixed

**Comment by keweishang** [comment]
I have the same request. Would support for `fixed` cannot be added, would it be possible to replace `fixed Foo(20);` with anything else?
