### ISSUE TITLE
Example of overriding ouputDir? 

### ISSUE THREAD

**Issue by ppearcy** [julianpeeters/sbt-avrohugger#6]
Heya,
  Sorry for the question in the form of a ticket that is likely just my lack of knowledge/general confusion with sbt, but I am really struggling setting overriding the outputDir. 

I saw that sbt-avro has an example to override here:
https://github.com/cavorite/sbt-avro

eg:

    seq( sbtavro.SbtAvro.avroSettings : _*)
    (stringType in avroConfig) := "String"

Here, stringType is a SettingKey so works. However, `outputDir` is a `sbt.Def.Setting` and I can't figure out how to get this magic to kick in. 

Any help would be appreciated and I can send a PR back to push this to the README.

Thanks!

**Comment by julianpeeters** [comment]
Oh hey Paul, good question.  As per the "Settings" table in the readme, the setting is "scalaSource", so try 

```
seq( sbtavro.SbtAvro.avroSettings : _*)

(scalaSource in avroConfig) := new java.io.File("myoutputdir")
```

That name hasn't been the clearest for me either, and now I see that it doesn't even make sense considering that now Java source can be generated for specific ENUM. 

I take it that you're nominating "outputDir"? I'll second that.

So, without strong objection, I'll close this ticket after:
1) Rename "scalaSource" setting to "outputDir"
2) Update Readme with an example
3) Add a `scripted` test to `src/sbt-test/projects...` to make sure it doesn't break in the future.

No obligations of course, thanks for the feedback!

**Comment by ppearcy** [comment]
As always, thanks Julian! 

No objections and sounds like a good plan. The example you gave me got me unstuck.

**Comment by julianpeeters** [comment]
OK excellent

**Comment by ppearcy** [comment]
Also worth mentioning, I am overriding the output dir because intellij 14 doesn't place nice and adds both src_managed and compiled_avro to project build paths and get duplicate errors. 

So, I'm now defaulting to:

    sbtavrohugger.SbtAvrohugger.specificAvroSettings
    (scalaSource in avroConfig) <<= sourceManaged

I don't know the pros and cons, but sourceManaged should be the default internally? 

Which works well with intellij. Also worth mentioning latest sbt seq() is deprecated. 

Thanks again.

**Comment by julianpeeters** [comment]
This is great info for me.

Hmm, worth thinking about generating directly into sourceManaged. I already feel guilty about dumping generated Java in with the generated Scala, and worry if number of records/enums gets very high, especially if a user is also generating other files like xml etc. I don't use intellij so I appreciate your insight. Did you happen to investigate if this can be handled from intellij? Maybe your workaround is the best for the time being? In the meantime I'll try to get a better sense of how important it is to keep sourceManaged clean.

**Comment by ppearcy** [comment]
Did a little more research, likely the code belongs in `src_managed/main`. This is where generated code for the play2 app I'm working on gets generated and seems to be the standard. 

Makes Intellij happy, too.

**Comment by julianpeeters** [comment]
Ah nice. Does that mean that `src_managed/main/compiled_avro` works in Intellij too? Or would you mind checking if you get a moment?

**Comment by ppearcy** [comment]
Sure, this works fine, too:
`(scalaSource in avroConfig) <<= sourceManaged { _ / "main"  / "compiled_avro" }`

Thanks!

**Comment by julianpeeters** [comment]
Wonderful. I'll see about making the changes, hopefully today.

**Comment by ppearcy** [comment]
Shoot, I was wrong, must have done something out of order. Intellij is not happy with `src_managed/main/compiled_avro`. Since I can override not a big deal, but might still be best to stick with `src_managed/main`.

**Comment by julianpeeters** [comment]
Ok, no prob at all. Yeah, I agree with `src_managed/main`, reasoning that it's best to have a default that works out-of-the-box for everybody, with the option to keep things cleaner for those who need it.

**Comment by julianpeeters** [comment]
Ok, checked off #2 and #3 from the above list. I left the setting as "scalaSource" because it's a predefined setting, and it looks to be [best practice](http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Reuse+existing+keys) to reuse existing keys (even when the output is mixed .java and .scala,as implied [here](http://www.scala-sbt.org/0.13/docs/Howto-Generating-Files.html#Generate+sources)).

version 0.4.1 will be syncing up with Maven Central in a couple hours.

Cheers
