### ISSUE TITLE
Regression between 2.0.0-RC19 and 2.0.0-RC20

### ISSUE THREAD

**Issue by enhan** [julianpeeters/sbt-avrohugger#75]
It seems that there is a regression between 2.0.0-RC19 and 2.0.0-RC20.
I am running SBT 1.3.3.
When I uptdate sbt-avrohugger to 2.0.0-RC20, I loose all the dependencies in Test scope. 
It works fine when setting back 2.0.0-RC19.

How to reproduce :
- create a new project with sbt via `sbt new scala/scala-seed.g8`
- add a file `project/plugins.sbt` with `addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC20")`
- in sbt shell run `test:compile`

reverting to 2.0.0-RC19 fixes it.

**Comment by julianpeeters** [comment]
Thank you @enhan !

Should be fixed now, in RC21. It's up at Sonatype now, should be syncing with maven central soon.

**Comment by enhan** [comment]
Thank you ! (both for fixing & for sbt-avrohugger )
