### ISSUE TITLE
Escaping of reserved keywords does not seem configurable or consistent

### ISSUE THREAD

**Issue by alstielow** [julianpeeters/sbt-avrohugger#85]
Hi @julianpeeters, 

I'm not sure if this is necessarily a bug, but is there a way to configure the escaping when a field name containing a reserved keyword is renamed?

For example:
Executing the `avroScalaGenerate` task from `sbt-avrohugger` plugin, version: `2.0.0-RC24`
```
{
  "type": "record",
  "name": "TestReservedKeywords",
  "namespace": "com.example",
  "fields": [
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "final",
      "type": "string"
    },
    {
      "name": "default",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    },
    {
      "name": "override",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    }
  ]
}
```
Produces the following case class (note the combination of `` and $ escaping):
```
final case class TestReservedKeywords(`type`: String, final$: String, default$: Option[Boolean] = None, `override`: Option[Boolean] = None)
```

Is there someway of producing the following the case class with consistent escaping using backticks?
```
final case class TestReservedKeywords(`type`: String, `final`: String, `default`: Option[Boolean] = None, `override`: Option[Boolean] = None)
```

**Comment by julianpeeters** [comment]
Sorry for delay and thank you for the report. Backticks are now the default reserved-word escaping in avrohugger 1.0.0 and sbt-avrohugger 2.0.0
