### ISSUE TITLE
 * can be used only for last argument

### ISSUE THREAD

**Issue by aksharp** [julianpeeters/sbt-avrohugger#89]
following code did not compile with Scala 3.1 giving the error " * can be used only for last argument"

`  def put(field$: Int, value: Any): Unit = {
    (field$: @switch) match {
      case 0 => this.linkedUserIds = {
        value match {
          case (array: java.util.List[_]) => {
            Seq((scala.jdk.CollectionConverters.IteratorHasAsScala(array.iterator).asScala.toSeq map { x =>
              x.toString
            }: _*))
          }
        }
      }.asInstanceOf[Seq[String]]
      case _ => new org.apache.avro.AvroRuntimeException("Bad index")
    }
    ()
  }`

avro type
`
            "type":{
                "type": "array",
                "items":{
                    "name":"userId",
                    "type":"string",
                    "default": ""
                }
            },
`

I modified 
`
            Seq((scala.jdk.CollectionConverters.IteratorHasAsScala(array.iterator).asScala.toSeq map { x =>
              x.toString
            }: _*))
`
to this to make it work
`
            scala.jdk.CollectionConverters.IteratorHasAsScala(array.iterator).asScala.toSeq map { x =>
              x.toString
            }
`

**Comment by xelax** [comment]
yep, I also got the error on a generated class when using scala 3.1.  in my case only if I use the `avroScalaGenerateSpecific`

**Comment by julianpeeters** [comment]
Thanks all, this should be fixed now in avrohugger 1.2.0 and sbt-avrohugger 2.2.0

**Comment by xelax** [comment]
thanks! i can confirm that it fixed the problem. Appreciated!
